services:
  # PostgreSQL Database with multiple databases support
  postgres:
    image: postgres:15
    container_name: taskmate_postgres
    environment:
      POSTGRES_USER: taskmate
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: user_service_db,task_service_db,analytics_service_db,file_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmate"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for session management and caching
  redis:
    image: redis:7-alpine
    container_name: taskmate_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    container_name: taskmate_user_service
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://taskmate:password@postgres:5432/user_service_db
      - DATABASE_HOST=postgres
      - DATABASE_USER=taskmate
      - REDIS_URL=redis://redis:6379/0
      - RAILS_MASTER_KEY_DUMMY=1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    networks:
      - default

  # Task Service  
  task-service:
    build:
      context: ./services/task-service
      dockerfile: Dockerfile
    container_name: taskmate_task_service
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://taskmate:password@postgres:5432/task_service_db
      - REDIS_URL=redis://redis:6379/1
      - USER_SERVICE_URL=http://user-service:3000
      - RAILS_MASTER_KEY_DUMMY=1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3001"]
    networks:
      - default

  # Analytics Service
  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    container_name: taskmate_analytics_service
    ports:
      - "3002:3002"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://taskmate:password@postgres:5432/analytics_service_db
      - REDIS_URL=redis://redis:6379/2
      - USER_SERVICE_URL=http://user-service:3000
      - TASK_SERVICE_URL=http://task-service:3001
      - RAILS_MASTER_KEY_DUMMY=1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      task-service:
        condition: service_started
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3002"]
    networks:
      - default

  # File Service
  file-service:
    build:
      context: ./services/file-service
      dockerfile: Dockerfile
    container_name: taskmate_file_service
    ports:
      - "3003:3003"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://taskmate:password@postgres:5432/file_service_db
      - REDIS_URL=redis://redis:6379/3
      - USER_SERVICE_URL=http://user-service:3000
      - TASK_SERVICE_URL=http://task-service:3001
      - RAILS_MASTER_KEY_DUMMY=1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      task-service:
        condition: service_started
    volumes:
      - file_uploads:/app/storage
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3003"]
    networks:
      - default

volumes:
  postgres_data:
  redis_data:
  file_uploads:

networks:
  default:
    name: taskmate_network