apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: taskmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: taskmate-user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: development
        - name: DATABASE_URL
          value: postgresql://taskmate:password@postgres-service:5432/user_service_db
        - name: DATABASE_HOST
          value: postgres-service
        - name: DATABASE_USER
          value: taskmate
        - name: REDIS_URL
          value: redis://redis-service:6379/0
        - name: RAILS_MASTER_KEY_DUMMY
          value: "1"
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: taskmate
spec:
  selector:
    app: user-service
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort