---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: taskmate-dev
  labels:
    app: user-service
    service: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        service: user
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5432 -U taskmate; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: redis:7-alpine
        command: ['sh', '-c', 'until redis-cli -h redis-service ping; do echo waiting for redis; sleep 1; done;']
      containers:
      - name: user-service
        image: taskmate/user-service:dev
        imagePullPolicy: Never  # Use locally built image
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/user_service_db"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: RAILS_MASTER_KEY_DUMMY
          value: "1"
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: taskmate-dev
  labels:
    app: user-service
    service: user
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: user-service
---
# NodePort service for external access during development
apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
  namespace: taskmate-dev
  labels:
    app: user-service
    service: user
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: user-service