---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: taskmate
  labels:
    app: analytics-service
    tier: application
    service: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        tier: application
        service: analytics
    spec:
      containers:
      - name: analytics-service
        image: taskmate/analytics-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
          name: http
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/analytics_service_db"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskmate-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_URL
          value: "redis://redis-service:6379/2"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: USER_SERVICE_URL
        - name: TASK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: TASK_SERVICE_URL
        - name: RAILS_MASTER_KEY_DUMMY
          value: "1"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /up
            port: 3002
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /up
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
      initContainers:
      - name: db-migrate
        image: taskmate/analytics-service:latest
        imagePullPolicy: Never
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/analytics_service_db"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskmate-secrets
              key: DATABASE_PASSWORD
        command: ["./bin/rails", "db:create", "db:migrate"]
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: taskmate
  labels:
    app: analytics-service
    tier: application
    service: analytics
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: analytics-service