---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploads-pvc
  namespace: taskmate
  labels:
    app: file-service
    tier: application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: taskmate
  labels:
    app: file-service
    tier: application
    service: file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        tier: application
        service: file
    spec:
      containers:
      - name: file-service
        image: taskmate/file-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/file_service_db"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskmate-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_URL
          value: "redis://redis-service:6379/3"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: USER_SERVICE_URL
        - name: TASK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: TASK_SERVICE_URL
        - name: RAILS_MASTER_KEY_DUMMY
          value: "1"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: file-uploads
          mountPath: /app/storage
        livenessProbe:
          httpGet:
            path: /up
            port: 3003
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /up
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: file-uploads
        persistentVolumeClaim:
          claimName: file-uploads-pvc
      restartPolicy: Always
      initContainers:
      - name: db-migrate
        image: taskmate/file-service:latest
        imagePullPolicy: Never
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/file_service_db"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskmate-secrets
              key: DATABASE_PASSWORD
        command: ["./bin/rails", "db:create", "db:migrate"]
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: taskmate
  labels:
    app: file-service
    tier: application
    service: file
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: file-service