---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: taskmate
  labels:
    app: frontend-service
    tier: frontend
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
        tier: frontend
        service: frontend
    spec:
      containers:
      - name: frontend-service
        image: taskmate/frontend-service:latest
        imagePullPolicy: Never
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3100"]
        ports:
        - containerPort: 3100
          name: http
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/frontend_service_db"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskmate-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_URL
          value: "redis://redis-service:6379/4"
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: USER_SERVICE_URL
        - name: TASK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: TASK_SERVICE_URL
        - name: ANALYTICS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: ANALYTICS_SERVICE_URL
        - name: FILE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: FILE_SERVICE_URL
        - name: RAILS_MASTER_KEY_DUMMY
          value: "1"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /up
            port: 3100
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /up
            port: 3100
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
      initContainers:
      - name: db-migrate
        image: taskmate/frontend-service:latest
        imagePullPolicy: Never
        env:
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: taskmate-config
              key: RAILS_ENV
        - name: DATABASE_URL
          value: "postgresql://taskmate:password@postgres-service:5432/frontend_service_db"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskmate-secrets
              key: DATABASE_PASSWORD
        command: ["./bin/rails", "db:create", "db:migrate"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: taskmate
  labels:
    app: frontend-service
    tier: frontend
    service: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http
  selector:
    app: frontend-service